FROM node:20

WORKDIR /app

# Install system dependencies for React Native DevTools
RUN apt-get update && apt-get install -y \
    libnspr4 \
    libnss3 \
    libdbus-1-3 \
    libatk1.0-0 \
    libatk-bridge2.0-0 \
    libcups2 \
    libdrm2 \
    libxkbcommon0 \
    libxcomposite1 \
    libxdamage1 \
    libxfixes3 \
    libxrandr2 \
    libgbm1 \
    libasound2 \
    libgtk-3-0 \
    libx11-xcb1 \
    && rm -rf /var/lib/apt/lists/*



# Install Expo CLI
RUN npm install -g expo-cli @expo/ngrok

# Copy package files first
COPY package*.json ./

RUN npm install

# Copy source code
COPY . .

ENV ELECTRON_NO_SANDBOX=1

EXPOSE 8081
EXPOSE 19000
EXPOSE 19001
EXPOSE 19002

CMD ["npx", "expo", "start", "--tunnel"]
